backend:
  name: github
  repo: afonsojramos/critical-mass
  branch: main
  site_domain: critical-mass.pages.dev
  base_url: https://critical-mass.pages.dev
  auth_endpoint: oauth

media_folder: "public/images/uploads"
public_folder: "/images/uploads"

site_url: https://critical-mass.pages.dev
logo_url: /logo.svg

i18n:
  structure: multiple_folders
  locales: [pt, en]
  default_locale: pt

collections:
  # Authors
  - name: "authors"
    label: "Authors"
    folder: "src/content/authors"
    create: true
    slug: "{{slug}}"
    extension: "json"
    format: "json"
    fields:
      - { label: "Name", name: "name", widget: "string" }
      - {
          label: "Image",
          name: "image",
          widget: "image",
          media_folder: "/public/images/authors",
          public_folder: "/images/authors",
        }
      - { label: "Bio", name: "bio", widget: "text", required: false }
      - { label: "Twitter", name: "twitter", widget: "string", required: false }
      - {
          label: "LinkedIn",
          name: "linkedin",
          widget: "string",
          required: false,
        }
      - { label: "GitHub", name: "github", widget: "string", required: false }

  # Portuguese Blog Posts
  - name: "blog_pt"
    label: "Blog (Português)"
    folder: "src/content/blog/pt"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "pubDate", widget: "datetime" }
      - {
          label: "Author",
          name: "author",
          widget: "relation",
          collection: "authors",
          search_fields: ["name"],
          value_field: "{{slug}}",
          display_fields: ["name"],
        }
      - {
          label: "Featured Image",
          name: "image",
          widget: "image",
          media_folder: "/public/images/articles",
          public_folder: "/images/articles",
        }
      - {
          label: "Tags",
          name: "tags",
          widget: "select",
          multiple: true,
          options:
            [
              "ciclismo",
              "ativismo",
              "história",
              "segurança",
              "dicas",
              "urbanismo",
              "comunidade",
              "eventos",
              "sustentabilidade",
              "mobilidade",
              "transporte",
              "bicicleta",
            ],
          default: [],
        }
      - { label: "Summary", name: "summary", widget: "text" }
      - {
          label: "Type",
          name: "type",
          widget: "select",
          options: ["Article", "Tutorial"],
          default: "Article",
        }
      - { label: "Body", name: "body", widget: "markdown" }

  # English Blog Posts
  - name: "blog_en"
    label: "Blog (English)"
    folder: "src/content/blog/en"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "pubDate", widget: "datetime" }
      - {
          label: "Author",
          name: "author",
          widget: "relation",
          collection: "authors",
          search_fields: ["name"],
          value_field: "{{slug}}",
          display_fields: ["name"],
        }
      - {
          label: "Featured Image",
          name: "image",
          widget: "image",
          media_folder: "/public/images/articles",
          public_folder: "/images/articles",
        }
      - {
          label: "Tags",
          name: "tags",
          widget: "select",
          multiple: true,
          options:
            [
              "cycling",
              "activism",
              "history",
              "safety",
              "tips",
              "urban planning",
              "community",
              "events",
              "sustainability",
              "mobility",
              "transport",
              "bicycle",
            ],
          default: [],
        }
      - { label: "Summary", name: "summary", widget: "text" }
      - {
          label: "Type",
          name: "type",
          widget: "select",
          options: ["Article", "Tutorial"],
          default: "Article",
        }
      - { label: "Body", name: "body", widget: "markdown" }

  # Portuguese Events
  - name: "events_pt"
    label: "Eventos (Português)"
    folder: "src/content/events/pt"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - {
          label: "Image",
          name: "image",
          widget: "image",
          required: false,
          media_folder: "/public/images/events",
          public_folder: "/images/events",
        }
      - { label: "Description", name: "description", widget: "text" }
      - {
          label: "Featured",
          name: "featured",
          widget: "boolean",
          default: false,
        }
      - { label: "Content", name: "body", widget: "markdown" }

  # English Events
  - name: "events_en"
    label: "Events (English)"
    folder: "src/content/events/en"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - {
          label: "Image",
          name: "image",
          widget: "image",
          required: false,
          media_folder: "/public/images/events",
          public_folder: "/images/events",
        }
      - { label: "Description", name: "description", widget: "text" }
      - {
          label: "Featured",
          name: "featured",
          widget: "boolean",
          default: false,
        }
      - { label: "Content", name: "body", widget: "markdown" }
