backend:
  name: github
  repo: afonsojramos/critical-mass
  branch: main
  site_domain: massacritica.pt
  base_url: https://massacritica.pt
  auth_endpoint: oauth

media_folder: "/src/assets/images"
public_folder: "/images"

site_url: https://massacritica.pt
logo_url: /logo.svg

i18n:
  structure: multiple_folders
  locales: [pt, en]
  default_locale: pt

collections:
  # Authors (Language neutral)
  - name: "authors"
    label: "Authors"
    folder: "src/content/authors"
    create: true
    slug: "{{slug}}"
    extension: "json"
    format: "json"
    media_folder: "/src/assets/images/authors"
    public_folder: "/images/authors"
    fields:
      - { label: "Name", name: "name", widget: "string" }
      - { label: "Image", name: "image", widget: "image" }
      - { label: "Bio", name: "bio", widget: "text", required: false }
      - {
          label: "Social Media Link",
          name: "socialMediaLink",
          widget: "string",
          required: false,
          hint: "Full URL (e.g., https://twitter.com/username, https://linkedin.com/in/username)",
        }

  # Blog Posts (Unified with i18n)
  - name: "blog"
    label: "Blog"
    folder: "src/content/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    media_folder: "/src/assets/images/articles"
    public_folder: "/images/articles"
    i18n: true
    fields:
      - { label: "Title", name: "title", widget: "string", i18n: true }
      - {
          label: "Publish Date",
          name: "pubDate",
          widget: "datetime",
          i18n: duplicate,
        }
      - {
          label: "Author",
          name: "author",
          widget: "relation",
          collection: "authors",
          search_fields: ["name"],
          value_field: "{{slug}}",
          display_fields: ["name"],
          i18n: duplicate,
        }
      - {
          label: "Featured Image",
          name: "image",
          widget: "image",
          i18n: duplicate,
        }
      - {
          label: "Tags",
          name: "tags",
          widget: "select",
          multiple: true,
          options:
            [
              "cycling",
              "activism",
              "history",
              "safety",
              "tips",
              "urban-planning",
              "community",
              "events",
              "sustainability",
              "mobility",
              "transport",
              "bicycle",
            ],
          default: [],
          i18n: duplicate,
        }
      - { label: "Summary", name: "summary", widget: "text", i18n: true }
      - {
          label: "Type",
          name: "type",
          widget: "select",
          options: ["Article", "Tutorial"],
          default: "Article",
          i18n: duplicate,
        }
      - { label: "Body", name: "body", widget: "markdown", i18n: true }

  # Events (Unified with i18n)
  - name: "events"
    label: "Events"
    folder: "src/content/events"
    create: true
    slug: "{{slug}}"
    media_folder: "/src/assets/images/events"
    public_folder: "/images/events"
    i18n: true
    fields:
      - { label: "Title", name: "title", widget: "string", i18n: true }
      - {
          label: "Images",
          name: "images",
          widget: "list",
          required: false,
          field: { label: "Image", name: "image", widget: "image" },
          i18n: duplicate,
        }
      - {
          label: "Description",
          name: "description",
          widget: "text",
          i18n: true,
        }
      - {
          label: "Featured",
          name: "featured",
          widget: "boolean",
          default: false,
          i18n: duplicate,
        }
      - { label: "Content", name: "body", widget: "markdown", i18n: true }

  # Gallery (Unified with i18n)
  - name: "gallery"
    label: "Gallery"
    folder: "src/content/gallery"
    create: true
    slug: "{{slug}}"
    extension: "json"
    format: "json"
    media_folder: "/src/assets/images/gallery"
    public_folder: "/images/gallery"
    i18n: true
    fields:
      - { label: "Title", name: "title", widget: "string", i18n: true }
      - {
          label: "Image",
          name: "image",
          widget: "image",
          i18n: duplicate,
        }
      - {
          label: "Description",
          name: "description",
          widget: "text",
          required: false,
          i18n: true,
        }
      - {
          label: "Category",
          name: "category",
          widget: "select",
          options: ["events", "rides", "activism", "community", "posters", "other"],
          required: false,
          i18n: duplicate,
        }
      - {
          label: "Date",
          name: "date",
          widget: "datetime",
          required: true,
          i18n: duplicate,
        }
      - {
          label: "Author",
          name: "author",
          widget: "relation",
          collection: "authors",
          search_fields: ["name"],
          value_field: "{{slug}}",
          display_fields: ["name"],
          required: false,
          i18n: duplicate,
        }
